server:
  port: 9002

spring:
  boot:
    admin:
      client:
        url: http://localhost:7779
  application:
    name: order-service
  rabbitmq:
    host: 192.168.199.132 # rabbitmq所在虚机地址
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true # 作为客户端需要注册到Eureka
    fetch-registry: true  # 作为客户端需要从Eureka获取注册信息
    service-url: # 客户端注册地址
      defaultZone: http://localhost:8888/eureka
  instance:
  # 优先使用该服务的IP地址注册到Eureka，在生产环境建议改为true
prefer-ip-address: true

feign:
  hystrix:
    enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}
[%thread] %-5level %logger{36} - traceId=%X{traceId:-}
spanId=%X{spanId:-} - %msg%n"